_target_: lidar_prod.tasks.building_validation.BuildingValidator

data_format: ${data_format}
use_final_classification_codes: true

shp_path: null

cluster:
  tolerance: 0.5 # meters
  min_points: 10

bd_uni_request:
  buffer: 50

# Associated Version(s) : M10.0-proto151_V1.0_epoch_40_Myria3DV3.0.1-proto151optimization
thresholds:
  min_confidence_confirmation: 0.6191657780743232 # min proba to validate a point
  min_frac_confirmation: 0.10007771078282046 # min fractin of confirmed points per group for confirmation
  min_frac_confirmation_factor_if_bd_uni_overlay: 0.5082397171199939 # relaxation factor to min proba when point is under BDUni vector
  min_uni_db_overlay_frac: 0.675004709337371 # min fraction of points  under BDUni vector per group for confirmation
  min_confidence_refutation: 0.7477148092712739 # min proba to refute a point
  min_frac_refutation: 0.9613067360728214 # min fractin of refuted points per group for confirmation
  min_entropy_uncertainty: 0.877764808329276 # min entropy to flag a point as uncertain
  min_frac_entropy_uncertain: 0.7818934987674271 # min fractin of uncertain points (based on entropy) per group to flag as uncertain
